services:
  api:
    build: .
    ports:
    - 8000:8000
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=appdb
      - COLLECTION_NAME=items
    depends_on:
      - db
  db:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data:
